disabled_rules: # rule identifiers to exclude from running

  # Number of function parameters should be low.
  - function_parameter_count

  # Lines should not span too many characters.
  - line_length

  # Type bodies should not span too many lines.
  - type_body_length

  # Complexity of function bodies should be limited.
  - cyclomatic_complexity

  # Files should not span too many lines.
  - file_length

opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - TableView

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods # default

# configurable rules can be customized from this configuration file
# binary rules can set their severity level

# Closure expressions should have a single space inside each brace.
closure_spacing: warning

# Force casts should be avoided.
force_cast: warning # implicitly

# Force unwrapping should be avoided.
force_unwrapping: warning

# Implicitly unwrapped optionals should be avoided when possible.
implicitly_unwrapped_optional: warning

# Functions and methods parameters should be either on the same line, or one per line.
multiline_parameters: warning

# Opening braces should be preceded by a single space and on the same line as the declaration.
opening_brace: warning

#Force tries should be avoided.
force_try:
  severity: warning # explicitly

# Functions bodies should not span too many lines.
function_body_length:
  warning: 100

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)